// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKzgqKUzJ5eQ-WycqxCoVhFdPb03Fl4A',
    appId: '1:348365247770:web:59db9e2dffefbb340ac8a3',
    messagingSenderId: '348365247770',
    projectId: 'exhibitionproject-fdba1',
    authDomain: 'exhibitionproject-fdba1.firebaseapp.com',
    storageBucket: 'exhibitionproject-fdba1.appspot.com',
    measurementId: 'G-SLR6YPTZL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1RlbpP-3bq3lklkeS0I_Ns9QDYBqYoBU',
    appId: '1:348365247770:android:ad181a42cc3c0adb0ac8a3',
    messagingSenderId: '348365247770',
    projectId: 'exhibitionproject-fdba1',
    storageBucket: 'exhibitionproject-fdba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2nFUrj_Ncq9B7HNZx-ltlr-jiSqhO84',
    appId: '1:348365247770:ios:544dc85e70e65ff90ac8a3',
    messagingSenderId: '348365247770',
    projectId: 'exhibitionproject-fdba1',
    storageBucket: 'exhibitionproject-fdba1.appspot.com',
    iosBundleId: 'com.example.exhibitionProject',
  );
}
